### ISSUE TITLE
Generalize SQL Connector

### ISSUE THREAD

**Issue by adminde** [isc-konstanz/lori#1]
The current SQL connector relies on MySQL syntax and could be generalized with `SQLAlchemy`.  
This [sample configuration set](https://github.com/user-attachments/files/16726499/conf.zip) for [Puma](https://github.com/isc-konstanz/puma) can be used for testing.

**Comment by mprasad10** [comment]
Added sqlalchemy wrapper which is compatible with mysql, postgres and mariadb.
